version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
networks:
  internal:
    driver: bridge