version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
  # wordpress:
  #   image: php:fpm-alpine
  #   networks:
  #     - internal
  #   volumes:
  #     - ./data/:/var/www/html/

  wordpress:
    build:
      context: wordpress
    # depends_on:
    #       - service_mariadb
    # ports:
    #       - 9000:9000
    volumes:
      - ./data/:/var/www/html/
    environment:
      - PS1
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - internal

  mariadb:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - 3306
      - 33060
    networks:
      - internal

networks:
  internal:
    driver: bridge

